# 定义版本，不指定默认为版本 1，新版本功能更多
version: '3'

services:
  # 名称
  server:
    # 镜像
    image: jyoketsu/my-site-server
    # 相当于 docker build .
    # build: .
    restart: unless-stopped
    # 定义环境变量，类似 -e
    environment:
      - PORT=8099
      - MONGO_URL=mongodb://mongo:27017/mySite?authSource=mySite
      - MONGO_USER=jyoketsu
      - MONGO_PASS=528931
    depends_on:
      - mongo
    ports:
      - 8099:8099

  # https://hub.docker.com/_/mongo
  mongo:
    image: mongo:5.0
    restart: unless-stopped
    volumes:
      # 在host创建左侧目录和.dbshell，用于记录历史，否则mongo会报无该路径或者文件
      - ./docker/mongo_home/mongodb:/home/mongodb
      # 映射数据目录
      - ./docker/mongo_data:/data/db
      # 映射dump目录
      - ./docker/mongo_data/dump:/dump
      # 映射初始化目录
      - ./docker/mongo-init:/docker-entrypoint-initdb.d
    ports:
      - 27017:27017
    command: [ --auth ]
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 528931
      MONGO_INITDB_DATABASE: mySite
      MONGO_USERNAME: jyoketsu
      MONGO_PASSWORD: 528931
